-- ====================================================================
-- REASONVISUAL - STRICT PRODUCTION SECURITY SCHEMA (SUPABASE)
-- Jalankan skrip SQL ini di:
-- Dashboard Supabase -> SQL Editor (ikon >_) -> New Query -> Run
-- ====================================================================

-- 1. Buat Tabel 'gallery'
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  tipe_media text not null default 'gambar',          -- 'gambar' atau 'video'
  sumber_media text not null,                        -- URL publik Supabase Storage / link YouTube / link IG Reel
  thumb_media text,                                  -- URL thumbnail Supabase Storage (opsional)
  cover_image text,                                  -- Cover khusus untuk card video (opsional)
  kategori text not null default 'travel',           -- 'travel', 'wedding', 'graduation', 'bali_ceremony'
  judul_en text not null default '',                 -- Judul Bahasa Inggris
  judul_id text not null default '',                 -- Judul Bahasa Indonesia
  urutan int default 0,                              -- Nomor urut sorting
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Aktifkan Row Level Security (RLS) pada tabel gallery
alter table public.gallery enable row level security;

-- Policy SELECT: Izinkan publik & pengunjung website untuk MEMBACA galeri
drop policy if exists "Allow public read access on gallery" on public.gallery;
create policy "Allow public read access on gallery"
  on public.gallery
  for select
  to anon, authenticated
  using (true);

-- Policy WRITE: HANYA ADMIN TERAUTENTIKASI (LOGIN RESMI SUPABASE)
-- Hacker atau siapapun dari luar yang mencoba POST / PATCH / DELETE dengan anon key akan DITOLAK KERAS!
drop policy if exists "Allow write access on gallery" on public.gallery;
drop policy if exists "Allow authenticated admin write gallery" on public.gallery;
create policy "Allow authenticated admin write gallery"
  on public.gallery
  for all
  to authenticated
  using (true)
  with check (true);

-- ====================================================================
-- 3. STORAGE BUCKET: Otomatis buat bucket 'gallery' dan jadikan Public
-- ====================================================================
insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do update set public = true;

-- Policy agar siapa saja bisa melihat foto publik di bucket gallery
drop policy if exists "Public read gallery bucket" on storage.objects;
create policy "Public read gallery bucket"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'gallery');

-- Policy agar HANYA ADMIN TERAUTENTIKASI yang bisa UPLOAD foto/thumbnail ke bucket gallery
drop policy if exists "Allow upload to gallery bucket" on storage.objects;
drop policy if exists "Allow authenticated admin upload gallery bucket" on storage.objects;
create policy "Allow authenticated admin upload gallery bucket"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'gallery');

-- Policy agar HANYA ADMIN TERAUTENTIKASI yang bisa DELETE foto/thumbnail dari bucket gallery
drop policy if exists "Allow delete from gallery bucket" on storage.objects;
drop policy if exists "Allow authenticated admin delete gallery bucket" on storage.objects;
create policy "Allow authenticated admin delete gallery bucket"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'gallery');

-- Policy agar HANYA ADMIN TERAUTENTIKASI yang bisa UPDATE/UPSERT foto/thumbnail di bucket gallery
drop policy if exists "Allow authenticated admin update gallery bucket" on storage.objects;
create policy "Allow authenticated admin update gallery bucket"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'gallery')
  with check (bucket_id = 'gallery');

-- ====================================================================
-- 4. TABEL 'categories': Master Kategori Dinamis
-- ====================================================================
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text unique not null,                         -- 'travel', 'wedding', 'aerial_drone', dll
  name text not null,                                -- 'Travel', 'Wedding', 'Aerial Drone', dll
  urutan int default 0,                              -- Nomor urut sorting
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Aktifkan RLS pada tabel categories
alter table public.categories enable row level security;

-- Policy SELECT: Izinkan siapa saja membaca kategori
drop policy if exists "Allow public read access on categories" on public.categories;
create policy "Allow public read access on categories"
  on public.categories
  for select
  to anon, authenticated
  using (true);

-- Policy WRITE: HANYA ADMIN TERAUTENTIKASI yang bisa menambah/mengedit/menghapus kategori
drop policy if exists "Allow write access on categories" on public.categories;
drop policy if exists "Allow authenticated admin write categories" on public.categories;
create policy "Allow authenticated admin write categories"
  on public.categories
  for all
  to authenticated
  using (true)
  with check (true);

-- Seed data awal kategori bawaan
insert into public.categories (slug, name, urutan) values
  ('wedding', 'Wedding', 1),
  ('bali_ceremony', 'Bali Ceremony', 2),
  ('travel', 'Travel', 3),
  ('graduation', 'Graduation', 4),
  ('villa_property', 'Villa & Property', 5),
  ('event', 'Event', 6)
on conflict (slug) do nothing;
